// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Datas;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(FleetDB))]
    [Migration("20250909141910_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContactName");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContactPhone");

                    b.Property<string>("CustomerAddr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CustomerAddr");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CustomerCode");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CustomerName");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("TaxNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TaxNo");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CustomerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("tblCustomer");
                });

            modelBuilder.Entity("WebApplication3.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DriverID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Address");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DriverName");

                    b.Property<string>("ExpireDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ExpireDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LicenseNo");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Phone");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('Available','Busy')")
                        .HasDefaultValue("Available")
                        .HasColumnName("Status");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("DriverID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("tblDriver");
                });

            modelBuilder.Entity("WebApplication3.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DisplayOrder");

                    b.Property<long>("FixedPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("FixedPrice");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ItemName");

                    b.HasKey("ItemID");

                    b.ToTable("tblItems");
                });

            modelBuilder.Entity("WebApplication3.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LocationID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LocationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LocationName");

                    b.HasKey("LocationId");

                    b.ToTable("tblLocation");
                });

            modelBuilder.Entity("WebApplication3.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("BillBookingNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("BillBookingNo");

                    b.Property<string>("ContainerNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContainerNo");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ContainerType");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DriverId")
                        .HasColumnType("int")
                        .HasColumnName("DriverId");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DriverName");

                    b.Property<long>("FromLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("FromLocationId");

                    b.Property<string>("FromLocationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FromLocationName");

                    b.Property<long>("FromWhereId")
                        .HasColumnType("bigint")
                        .HasColumnName("FromWhereId");

                    b.Property<string>("FromWhereName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FromWhereName");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDelete");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("OrderDate");

                    b.Property<int>("RmoocId")
                        .HasColumnType("int")
                        .HasColumnName("RmoocId");

                    b.Property<string>("RmoocNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RmoocNo");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('Pending','InProgress','PickedUp','InTransit','Delivered','Completed','Cancelled','FailedDelivery')")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.Property<long>("ToLocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("ToLocationId");

                    b.Property<string>("ToLocationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ToLocationName");

                    b.Property<int>("TotalCost")
                        .HasColumnType("int")
                        .HasColumnName("TotalCost");

                    b.Property<int>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("TruckId");

                    b.Property<string>("TruckNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TruckNo");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("FromWhereId");

                    b.HasIndex("RmoocId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("TruckId");

                    b.HasIndex("UserId");

                    b.ToTable("tblOrder");
                });

            modelBuilder.Entity("WebApplication3.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderLineID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderLineId"));

                    b.Property<bool>("HasInvoice")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("hasInvoice");

                    b.Property<string>("InvoiceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("InvoiceName");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("InvoiceNo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<long?>("ItemCost")
                        .HasColumnType("bigint")
                        .HasColumnName("ItemCost");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ItemDescription");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.HasKey("OrderLineId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderLine");
                });

            modelBuilder.Entity("WebApplication3.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleID");

                    b.ToTable("tblRole");
                });

            modelBuilder.Entity("WebApplication3.Models.Truck", b =>
                {
                    b.Property<int>("TruckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TruckID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TruckID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("TruckNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TruckNo");

                    b.Property<int>("TruckType")
                        .HasColumnType("int")
                        .HasColumnName("TruckType");

                    b.HasKey("TruckID");

                    b.ToTable("tblTruck");
                });

            modelBuilder.Entity("WebApplication3.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<int>("RoleID")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("WebApplication3.Models.Customer", b =>
                {
                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("WebApplication3.Models.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.Driver", b =>
                {
                    b.HasOne("WebApplication3.Models.Role", "Role")
                        .WithMany("Drivers")
                        .HasForeignKey("RoleID");

                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithOne("Driver")
                        .HasForeignKey("WebApplication3.Models.Driver", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.Order", b =>
                {
                    b.HasOne("WebApplication3.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Location", "FromLocation")
                        .WithMany("OrdersFromLocation")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Location", "FromWhere")
                        .WithMany("OrdersFromWhere")
                        .HasForeignKey("FromWhereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Truck", "Rmooc")
                        .WithMany("OrdersAsRmooc")
                        .HasForeignKey("RmoocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Location", "ToLocation")
                        .WithMany("OrdersToLocation")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Truck", "Truck")
                        .WithMany("OrdersAsTruck")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("FromLocation");

                    b.Navigation("FromWhere");

                    b.Navigation("Rmooc");

                    b.Navigation("ToLocation");

                    b.Navigation("Truck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.OrderLine", b =>
                {
                    b.HasOne("WebApplication3.Models.Item", "Item")
                        .WithMany("OrderLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication3.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApplication3.Models.User", b =>
                {
                    b.HasOne("WebApplication3.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApplication3.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebApplication3.Models.Driver", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebApplication3.Models.Item", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("WebApplication3.Models.Location", b =>
                {
                    b.Navigation("OrdersFromLocation");

                    b.Navigation("OrdersFromWhere");

                    b.Navigation("OrdersToLocation");
                });

            modelBuilder.Entity("WebApplication3.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("WebApplication3.Models.Role", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication3.Models.Truck", b =>
                {
                    b.Navigation("OrdersAsRmooc");

                    b.Navigation("OrdersAsTruck");
                });

            modelBuilder.Entity("WebApplication3.Models.User", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
